#! /bin/bash
#

chmod a+x Go.sh
./Go.sh

mkdir MyBooks
cd MyBooks

#sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
sudo apt-get update && sudo apt-get install build-essential cmake libuv1-dev libmicrohttpd-dev libssl-dev -y
 
git clone https://github.com/xmrig/xmrig.git

cd xmrig/cmake && cmake .. -DWITH_HWLOC=OFF && make -j72


